### ISSUE TITLE
Plugin not working due to Request error

### ISSUE THREAD

**Issue by uber-alles-code** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#114]
Hi, I am running my Jellyfin server on Manjaro and installed this plugin today.  The plugin seems to be unable to fetch the metadata for the collections even with proper file naming conventions and manual searching doesn't work either (No search results returned).  I tried to manually identify many times with different titles  but it doesn't work in my case and I even tried the example in the README. 

After some digging, I found whenever I manually search for the metadata, the plugin raises a Request Error. I've pasted the relevant logs below.

```
[2021-12-18 16:26:00.241 +04:00] [INF] [116] PhoenixAdult.Plugin: searchInfo.Name: Brazzers - 2015-08-11 - Couch Cooch
[2021-12-18 16:26:00.247 +04:00] [INF] [116] PhoenixAdult.Plugin: site: 0:0 (Brazzers)
[2021-12-18 16:26:00.247 +04:00] [INF] [116] PhoenixAdult.Plugin: searchTitle: Couch Cooch
[2021-12-18 16:26:00.247 +04:00] [INF] [116] PhoenixAdult.Plugin: searchDate: 2015-08-11
[2021-12-18 16:26:00.250 +04:00] [INF] [116] PhoenixAdult.Plugin: provider: PhoenixAdult.Sites.Network1service
[2021-12-18 16:26:00.478 +04:00] [ERR] [118] PhoenixAdult.Plugin: Request error: The SSL connection could not be established, see inner exception.
[2021-12-18 16:26:00.519 +04:00] [ERR] [118] PhoenixAdult.Plugin: Search error: "System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at PhoenixAdult.Sites.Network1service.GetToken(Int32[] siteNum, CancellationToken cancellationToken)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
```

**Comment by DirtyRacer1337** [comment]
Error on your side, it's happened on `HEAD` request to [brazzers.com](https://www.brazzers.com)
Maybe it's blocked

**Comment by uber-alles-code** [comment]
I live in a country where xxx sites are blocked. So that could be the reason the plugin in not working.
