### ISSUE TITLE
[Error] Plugin is not able to fetch any data

### ISSUE THREAD

**Issue by roshanconnor123** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#14]
Hi
I got this error after Installation of this Plugin
```
[2020-08-11 18:13:16.717 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loaded assembly "PhoenixAdult, Version=2.1.2.30, Culture=neutral, PublicKeyToken=null" from "C:\ProgramData\Jellyfin\Server\plugins\PhoenixAdult\Jellyfin.Plugin.PhoenixAdult.dll"
[2020-08-11 18:13:23.201 +00:00] [FTL] [1] Main: Error while starting server.
Busy: SQLitePCL.pretty.SQLiteException: database is locked
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3_stmt stmt, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at SQLitePCL.pretty.DatabaseConnection.Execute(IDatabaseConnection This, String sql)
   at Emby.Server.Implementations.Data.BaseSqliteRepository.GetConnection(Boolean _)
   at Emby.Server.Implementations.Data.SqliteItemRepository.Initialize(SqliteUserDataRepository userDataRepo, IUserManager userManager)
   at Emby.Server.Implementations.ApplicationHost.InitializeServices()
   at Jellyfin.Server.Program.StartApp(StartupOptions options)
[2020-08-11 18:13:23.367 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost
```
Is there any way to fix this
Thanks

**Comment by DirtyRacer1337** [comment]
`database is locked` better ask on jellyfin developers https://github.com/jellyfin/jellyfin

But, uou probably run two jellyfin copies

**Comment by roshanconnor123** [comment]
> `database is locked` better ask on jellyfin developers https://github.com/jellyfin/jellyfin
> 
> But, you probably run two jellyfin copies

Hey man
So it got Fixed by itself after some time
Everything is cool now
Got that sweet metadata too
Thank you
