### ISSUE TITLE
Identifying FreeUseMILF videos crashes Jellyfin

### ISSUE THREAD

**Issue by sjiawjbssj** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#161]
Identifying videos from FreeUseMILF crashes Jellyfin.
This issue only happens with that site as far as I noticed. Adding it via ThePornDB works fine.
I think this issue started after Jellyfin 10.8.

<details><summary>Here are the logs from Jellyfin:</summary>
<p>

[2022-08-06 03:24:05.952 +02:00] [INF] [62] PhoenixAdult.Plugin: provider: PhoenixAdult.Sites.NetworkMylf
[2022-08-06 03:24:09.208 +02:00] [INF] [144] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : "f2bd2098235c0ccae4e630cc5a72e9a725982937-cb656eddecc74c15b28c03c93aca1545-70d5cb8b4fbfdbeb07ec394fec0a5115"
[2022-08-06 03:24:10.027 +02:00] [WRN] [30] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.178.31:8096/Items/RemoteSearch/Movie" to "192.168.178.24" in 0:00:04.146574 with Status Code 200
[2022-08-06 03:24:12.137 +02:00] [INF] [143] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item bc673636-df2c-0e88-eb44-b026d606a913-"FreeUseMilf_First Impressions": "{\"PhoenixAdult\":\"24#62#L5rzTZrx6xmiPBnzanh4uwXwGU9WFt3Ti2\"}"
[2022-08-06 03:24:21.113 +02:00] [INF] [30] PhoenixAdult.Plugin: PhoenixAdult ID: 24#62#L5rzTZrx6xmiPBnzanh4uwXwGU9WFt3Ti2
[2022-08-06 03:24:24.666 +02:00] [FTL] [144] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'buffer')
   at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
   at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
   at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)

</p>
</details>

<details><summary>And here are the logs from docker:</summary>
<p>

[03:24:05] [INF] [62] PhoenixAdult.Plugin: searchInfo.Name: FreeUseMilf - First Impressions
[03:24:05] [INF] [62] PhoenixAdult.Plugin: site: 24:62 (FreeuseMILF)
[03:24:05] [INF] [62] PhoenixAdult.Plugin: searchTitle: First Impressions
[03:24:05] [INF] [62] PhoenixAdult.Plugin: searchDate:
[03:24:05] [INF] [62] PhoenixAdult.Plugin: provider: PhoenixAdult.Sites.NetworkMylf
[03:24:09] [INF] [144] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Processing playback tracker : f2bd2098235c0ccae4e630cc5a72e9a725982937-cb656eddecc74c15b28c03c93aca1545-70d5cb8b4fbfdbeb07ec394fec0a5115
[03:24:10] [WRN] [30] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.178.31:8096/Items/RemoteSearch/Movie to 192.168.178.24 in 0:00:04.146574 with Status Code 200
[03:24:12] [INF] [143] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item bc673636-df2c-0e88-eb44-b026d606a913-FreeUseMilf_First Impressions: {"PhoenixAdult":"24#62#L5rzTZrx6xmiPBnzanh4uwXwGU9WFt3Ti2"}
[03:24:21] [INF] [30] PhoenixAdult.Plugin: PhoenixAdult ID: 24#62#L5rzTZrx6xmiPBnzanh4uwXwGU9WFt3Ti2
[03:24:24] [FTL] [144] Main: Unhandled Exception
System.ArgumentNullException: Value cannot be null. (Parameter 'buffer')
at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'buffer')
at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
[03:24:25] [INF] [1] Main: Jellyfin version: 10.8.1

</p>
</details>

Jellyfin version: 10.8.1
Plugin version: 2.7.0.47
Scene URL: https://www.freeusemilf.com/movies/first-impressions
File name: FreeUseMilf_First Impressions_1080p

**Comment by DirtyRacer1337** [comment]
This should help cc5ae817d622d6737f94ea170118afe07f024f7e
