### ISSUE TITLE
Vixen search broken, other Strike3 sites work

### ISSUE THREAD

**Issue by rbronco** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#214]
1. Emby
2. from 6.20.23
3. [Scene URL](https://www.vixen.com/videos/wanting-to-get-caught)
4. Vixen - Wanting To Get Caught
5. see below, no info from the Tushy search, but there is no error

```
2023-07-03 03:19:43.191 Info PhoenixAdult: searchInfo.Name: Vixen - Wanting To Get Caught
2023-07-03 03:19:43.253 Info PhoenixAdult: site: 44:2 (Vixen)
2023-07-03 03:19:43.253 Info PhoenixAdult: searchTitle: Wanting To Get Caught
2023-07-03 03:19:43.253 Info PhoenixAdult: searchDate: 
2023-07-03 03:19:43.256 Info PhoenixAdult: provider: PhoenixAdult.Sites.NetworkStrike3
2023-07-03 03:19:43.421 Error PhoenixAdult: Request error: Exception: System.NotSupportedException: The 'unraid' scheme is not supported.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass10_0.<<SendFlareSolverrRequest>b__0>d.MoveNext()
```

```
2023-07-03 03:21:24.147 Info PhoenixAdult: searchInfo.Name: Tushy - Wanting To Get Caught
2023-07-03 03:21:24.150 Info PhoenixAdult: site: 44:3 (Tushy)
2023-07-03 03:21:24.150 Info PhoenixAdult: searchTitle: Wanting To Get Caught
2023-07-03 03:21:24.150 Info PhoenixAdult: searchDate: 
2023-07-03 03:21:24.150 Info PhoenixAdult: provider: PhoenixAdult.Sites.NetworkStrike3
2023-07-03 03:21:24.973 Info Server: http/2 Response 200 to host2. Time: 830ms. https://host1/emby/Items/RemoteSearch/Movie?X-Emby-Client=Emby Web&X-Emby-Device-Name=Google Chrome Windows&X-Emby-Device-Id=a9f8e05b-2743-43ce-9071-0ab36875e5c3&X-Emby-Client-Version=4.7.13.0&X-Emby-Language=en-us&reqformat=json
```

**Comment by DirtyRacer1337** [comment]
CloudFlare protection use `FlareSolverr`, it might doesn't work
