### ISSUE TITLE
MYLF & related sites unable to populate metadata

### ISSUE THREAD

**Issue by thesharingbro** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#250]
**Describe the bug**
MYLF & related sites unable to populate metadata
**Include**
1. Jellyfin
2. Plugin Version:  2.7.0.47
3. Scene URL:  https://members.mylf.com/m/20748
4. File Name: milfty unorthodox muff methods pristine edge 1080hd
5. 2 part issue:
1. Some Mylf and related sites are facing an issue wherein the metadata isn't being fetched. 
```
[2023-12-13 03:17:04.274 -05:00] [INF] [72] Emby.Server.Implementations.Library.LibraryManager: Found duplicate path: "/sharingbrother/MYLF/PervMom"
[2023-12-13 03:17:05.774 -05:00] [ERR] [72] Emby.Server.Implementations.Library.LibraryManager: Cannot compute blurhash for "/sharingbrother/MYLF/MomSwap.23.09.25.Mandy.Waters.And.Spencer.Scott.Breaking.The.Fast.XXX.2160p.MP4-XXX[XC]/folder.jpg"
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlurHashSharp.SkiaSharp.BlurHashEncoder.Encode(Int32 xComponent, Int32 yComponent, String filename, Int32 maxWidth, Int32 maxHeight)
   at Jellyfin.Drawing.Skia.SkiaEncoder.GetImageBlurHash(Int32 xComp, Int32 yComp, String path)
   at Emby.Drawing.ImageProcessor.GetImageBlurHash(String path, ImageDimensions imageDimensions)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateImagesAsync(BaseItem item, Boolean forceUpdate)
```
2. If tried manually, the data isn't being populated
```
2023-12-13 20:31:48.925520+00:00[15:31:48] [INF] [29] PhoenixAdult.Plugin: searchInfo.Name: mylfclassics Looking To Snuggle 
2023-12-13 20:31:48.936146+00:00[15:31:48] [INF] [29] PhoenixAdult.Plugin: site: 23:0 (Mylf)
2023-12-13 20:31:48.936190+00:00[15:31:48] [INF] [29] PhoenixAdult.Plugin: searchTitle: classics Looking To Snuggle
2023-12-13 20:31:48.936198+00:00[15:31:48] [INF] [29] PhoenixAdult.Plugin: searchDate: 
2023-12-13 20:31:48.937149+00:00[15:31:48] [INF] [29] PhoenixAdult.Plugin: provider: PhoenixAdult.Sites.NetworkMylf
2023-12-13 20:31:54.128181+00:00[15:31:54] [INF] [32] Jellyfin.Api.Controllers.ItemLookupController: Setting provider id's to item 8bdc3cde-346d-9b86-f0cf-3b3ed5a8d977-mylfclassics  Looking To Snuggle  jane doux 1080hd: {"PhoenixAdult":"23#0#2TETecG3UDKAc9MvZjd19EYdmfZi9VcEXTFr"}
2023-12-13 20:31:59.531616+00:00[15:31:59] [INF] [30] PhoenixAdult.Plugin: PhoenixAdult ID: 23#0#2TETecG3UDKAc9MvZjd19EYdmfZi9VcEXTFr
2023-12-13 20:32:00.573392+00:00[15:32:00] [FTL] [11] Main: Unhandled Exception
2023-12-13 20:32:00.573472+00:00System.ArgumentNullException: Value cannot be null. (Parameter 'buffer')
2023-12-13 20:32:00.573486+00:00at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
2023-12-13 20:32:00.573496+00:00at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
2023-12-13 20:32:00.573505+00:00at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
2023-12-13 20:32:00.923105+00:00Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'buffer')
2023-12-13 20:32:00.923138+00:00at SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
2023-12-13 20:32:00.923148+00:00at SkiaSharp.SKManagedStream.OnRead(IntPtr buffer, IntPtr size)
2023-12-13 20:32:00.923167+00:00at SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
```

**Comment by jonjon09** [comment]
Same issue here. It is causing my server to reboot every 2 minutes. When I manually try to fetch the metadata, it finds and populates it for about 2 seconds, then the server crashes and when it comes back up, the metadata is gone. And the cycle repeats itself.

**Comment by DatNglp** [comment]
Same issue, when it throws NE, server restarts, but it does not happen with nightly build running in Jellyfin 10.9.7
