### ISSUE TITLE
Method not found: 'System.String MediaBrowser.Controller.Entities.PersonInfo.get_Type()'

### ISSUE THREAD

**Issue by Nizno877** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#275]
**Describe the bug**
The logs are spammed with 
```logviewer[2024-06-11 19:37:49.587 +02:00] [ERR] [23] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "PhoenixAdult"
System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Entities.PersonInfo.get_Type()'.
   at PhoenixAdult.Helpers.Actors.Cleanup(MetadataResult`1 scene)
   at PhoenixAdult.Providers.MovieProvider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

**Include**
1. Jellyfin: 10.9.6
2. Plugin Version : 2.7.0.47
3. Scene URL - any
4. File Name - any
5. Log File - any

**Comment by SponkenDude** [comment]
Exact same issue here
