### ISSUE TITLE
"Cleanup Actors" fails

### ISSUE THREAD

**Issue by Jack20947** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#282]
The scheduled task "Cleanup Actors" fails with this error:

> [2024-12-24 20:40:36.260 +01:00] [ERR] Error executing Scheduled Task
> System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Entities.PersonInfo.get_Type()'.
>    at PhoenixAdult.Helpers.Actors.Cleanup(MetadataResult`1 scene)
>    at PhoenixAdult.ScheduledTasks.CleanupActors.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
>    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
> [2024-12-24 20:40:36.271 +01:00] [INF] "Cleanup Actors" Failed after 0 minute(s) and 9 seconds

**Include**
1. Jellyfin 10.10.3
2. 2.7.0.47

Let me know if you need more informations.

**Comment by michael-zock** [comment]
Still broken in 10.11.5, but it fails with this:

```
[2025-12-24 11:09:04.301 +01:00] [ERR] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.MissingMethodException: Method not found: 'System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.BaseItem> MediaBrowser.Controller.Library.ILibraryManager.GetItemList(MediaBrowser.Controller.Entities.InternalItemsQuery)'.
   at MonoMod.Core.Interop.CoreCLR.V60.InvokeCompileMethod(IntPtr functionPtr, IntPtr thisPtr, IntPtr corJitInfo, CORINFO_METHOD_INFO* methodInfo, UInt32 flags, Byte** nativeEntry, UInt32* nativeSizeOfCode)
   at MonoMod.Core.Platforms.Runtimes.Core60Runtime.JitHookDelegateHolder.CompileMethodHook(IntPtr jit, IntPtr corJitInfo, CORINFO_METHOD_INFO* methodInfo, UInt32 flags, Byte** nativeEntry, UInt32* nativeSizeOfCode)
   at PhoenixAdult.ScheduledTasks.CleanupActors.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at PhoenixAdult.ScheduledTasks.CleanupActors.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2025-12-24 11:09:04.303 +01:00] [INF] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Cleanup Actors" Failed after 0 minute(s) and 0 seconds

```
