### ISSUE TITLE
Search error: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by npr0n** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#31]
**Describe the bug**
After triggering a metadata update for multiple files, neither the triggered update, nor manual identification works. Tested for Pornhub. Relevant Jellyfin logs attached.

**Include**
1. Scene URL (example, first one in logfile)
https://www.pornhub.com/view_video.php?viewkey=ph5bde29663c716
2. File Name
"Pornhub - ph5bde29663c716.mp4"
3. Log File
[object reference.txt](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/files/5743326/object.reference.txt)

**Comment by DirtyRacer1337** [comment]
Works for me on latest version, is this happens for any scene?

**Comment by npr0n** [comment]
Happens for every scene. I am using jellyfin with the repository plugin.
Jellyfin version 10.6.4 (stable) on ubuntu server 20.04.
Plugin version 2.3.6.40 (from repository).

The errors only happen, when I first try to update metadata for multiple scenes (manual select or whole library) and choose to either update missing or replace all metadata. Then the plugin seems to "hang" for several minutes, where manual identification throws the errors from the log.
After 15-20 minutes I can do manual identification again, but the previous scan did nothing. For that I have not found anything in the jellyfin logs. 

I will try the dev version and report back! Thanks in advance, you are doing outstanding work!!! Ɛ>

**Comment by emptyellipsis** [comment]
Just came here to see if anyone else is seeing this and sure enough, I'm also seeing this on the current release with a bunch of Nubiles content.

```
[2021-01-05 19:37:03.223 +00:00] [INF] searchInfo.Name: phdp.20.07.15.light.fairy.some.like.it.rough
[2021-01-05 19:37:03.226 +00:00] [INF] newTitle: Phdp 20 07 15 Light Fairy Some Like It Rough
[2021-01-05 19:37:03.228 +00:00] [INF] site: 30:7 (PetiteHDPorn)
[2021-01-05 19:37:03.228 +00:00] [INF] searchTitle: Light Fairy Some Like It Rough
[2021-01-05 19:37:03.228 +00:00] [INF] searchDate: 2020-07-15
[2021-01-05 19:37:03.228 +00:00] [INF] provider: PhoenixAdult.Sites.NetworkNubiles
[2021-01-05 19:37:03.712 +00:00] [INF] Search error: "Object reference not set to an instance of an object."
[2021-01-05 19:37:03.713 +00:00] [ERR] System.NullReferenceException: Object reference not set to an instance of an object.
   at PhoenixAdult.Sites.NetworkNubiles.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
```

**Comment by DirtyRacer1337** [comment]
@emptyellipsis Try on dev version from message above and send logs if it fail again.
For me you example works.

Tried on on latest release, I don't know that's was wrong but it's fixed on dev version.
