### ISSUE TITLE
Plugin is not working anymore with Emby Beta above version 4.6.0.20

### ISSUE THREAD

**Issue by shocker2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#34]
There were lots of changes in 4.6.0.20 and I think the plugin needs to be updated.
If I'm testing the plugin with a known matching library, everything works fine with 4.6.0.10, if I upgrade to 4.6.0.20 I'm getting those errors:

```
2021-01-28 15:01:51.740 Error ProviderManager: ImageProvider failed in GetImageInfos for type Movie
        *** Error Report ***
        Version: 4.6.0.20
        Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-rpm_{version}_x86_64.rpm
        Operating system: Linux version 4.4.248-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) ) #1 SMP Thu Dec 10 18:28:07 EST 2
        Framework: .NET Core 3.1.8
        OS/Process: x64/x64
        Runtime: opt/emby-server/system/System.Private.CoreLib.dll
        Processor count: 48
        Data path: /var/lib/emby
        Application path: /opt/emby-server/system
        System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
           at PhoenixAdult.ImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
           at PhoenixAdult.ImageProvider.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken)
           at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, LibraryOptions libraryOptions, CancellationToken cancellationToken, IRemoteImageProvider provider, Int32 providerIndex)
        Source: PhoenixAdult
        TargetSite: Void MoveNext()
```

**Comment by DirtyRacer1337** [comment]
I'm not supporting beta versions, use stable release.

**Comment by shocker2** [comment]
> I'm not supporting beta versions, use stable release.

Don't get me wrong, it was not a complaint, just a heads-up that they changed the structure :)

**Comment by DirtyRacer1337** [comment]
Don't worry, this errors type will be found on compile.

They still not posted actual beta version of [MediaBrowser.Server.Core](https://www.nuget.org/packages/MediaBrowser.Server.Core/)

**Comment by shocker2** [comment]
> Don't worry, this errors type will be found on compile.
> 
> They still not posted actual beta version of [MediaBrowser.Server.Core](https://www.nuget.org/packages/MediaBrowser.Server.Core/)

Cool, thanks for the feedback!

**Comment by DirtyRacer1337** [comment]
Should work now on [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)
