### ISSUE TITLE
Brazzers Metadata Lookup Failing

### ISSUE THREAD

**Issue by GotRoses** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#36]
**Describe the bug**
Since yesterday, metadata lookups for Brazzers appear to be failing with a System.InvalidOperationException error.

**Include**
1. Jellyfin or Emby: Jellyfin 10.6.4 on Linx/Arm64
2. Plugin Version: 2.4.2.42
3. Scene URL: https://www.brazzers.com/video/4427681/a-naughty-nuru-massage
4. File Name: Brazzers - 4427681 - A Naughty Nuru Massage.mp4
5. Log File:

```
[2021-02-21 05:42:37.786 +00:00] [INF] [120] PhoenixAdult.Provider: searchInfo.Name: Brazzers - 4427681 - A Naughty Nuru Massage
[2021-02-21 05:42:37.805 +00:00] [INF] [120] PhoenixAdult.Provider: site: 0:0 (Brazzers)
[2021-02-21 05:42:37.805 +00:00] [INF] [120] PhoenixAdult.Provider: searchTitle: 4427681 A Naughty Nuru Massage
[2021-02-21 05:42:37.805 +00:00] [INF] [120] PhoenixAdult.Provider: searchDate: 
[2021-02-21 05:42:37.805 +00:00] [INF] [120] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-21 05:42:37.806 +00:00] [DBG] [120] PhoenixAdult.Provider: Requesting GET "https://site-api.project1service.com/v2/releases?type=scene&id=4427681"
[2021-02-21 05:42:38.513 +00:00] [ERR] [102] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
```

**Comment by DirtyRacer1337** [comment]
Fixed in 0149d5f0c13b3ca05ef2854869367478e2428cc3

**Comment by GotRoses** [comment]
Excellent news, thanks a lot!

**Comment by josst10** [comment]
Thanks, man. 

When you get to it you get to it! 

Thanks again.
