### ISSUE TITLE
"Identify" doesn't seem to be working

### ISSUE THREAD

**Issue by zkvvoob** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#37]
**Describe the bug**
When I open "Identify" for a particular clip and even if I enter the full URL of the scene, there are no results. I've tried with various combinations of studio, actress, scene name and year - still the same effect.

What I'm trying to figure out is, is there a way to force the plugin to scrape its database once I've added some more info, in addition to what's contained in the file name?

**Include**
1. Jellyfin: 10.6.4
2. Plugin Version: 2.4.2.42
3. Scene URL: https://www.brazzers.com/video/4024021/chores-for-a-whore
4. File Name: Brazzers - 2013-01-08 - Chores for a Whore - Rikki Six
5. Log File: I think this is the relevant section.

```
[2021-02-21 20:13:13.128 +00:00] [ERR] [24] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Unable to find the specified file". URL: "http://myjellifin.com/socket?deviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODEuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84MS4wfDE2MDIyMzk1Mjg3OTE1"
[2021-02-21 20:13:18.035 +00:00] [INF] [24] PhoenixAdult.Provider: searchInfo.Name: Brazzers - 2013-01-08 - Chores for a Whore - Rikki Six
[2021-02-21 20:13:18.040 +00:00] [INF] [24] PhoenixAdult.Provider: site: 0:0 (Brazzers)
[2021-02-21 20:13:18.040 +00:00] [INF] [24] PhoenixAdult.Provider: searchTitle: Chores For A Whore Rikki Six
[2021-02-21 20:13:18.040 +00:00] [INF] [24] PhoenixAdult.Provider: searchDate: 2013-01-08
[2021-02-21 20:13:18.041 +00:00] [INF] [24] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-21 20:13:19.074 +00:00] [ERR] [35] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
[2021-02-21 20:13:19.076 +00:00] [WRN] [35] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "185.94.192.180". Time (slow): 0:00:01.0562938. "http://myjellifin.com/Items/RemoteSearch/Movie"
[2021-02-21 20:13:26.234 +00:00] [INF] [24] PhoenixAdult.Provider: site: 43:0 (Freeones)
[2021-02-21 20:13:26.234 +00:00] [INF] [24] PhoenixAdult.Provider: actorName: Rikki Six
[2021-02-21 20:13:26.234 +00:00] [INF] [24] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.ActorFreeones
[2021-02-21 20:13:27.036 +00:00] [INF] [22] PhoenixAdult.Provider: PhoenixAdult Actor ID: 43#0#2y9D2HRfZhnquUrw2uhCP55zC
[2021-02-21 20:13:27.819 +00:00] [INF] [36] PhoenixAdult.Provider: Searching actor images for "Rikki Six"
[2021-02-21 20:13:35.215 +00:00] [WRN] [42] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "185.94.192.180". Time (slow): 0:00:09.0367918. "http://myjellifin.com/Users/9759fb32efa74fa4afd980cb441c03d3/Items/6191b7ae9a13ded92879c9bf41ed40a5"
[2021-02-21 20:13:40.264 +00:00] [ERR] [22] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: "Could not find a part of the path '/test/Albinoni/Albinoni - Oboe Concertos/folder.jpg'". URL: "http://myjellifin.com/Items/6aa5c9eca9eb3bd803527fed2b68a0cd/Images/Primary?maxHeight=660&maxWidth=660&tag=04d05a12b553e7eed15b4a4afc88ef0a&quality=90"
[2021-02-21 20:14:38.947 +00:00] [INF] [11] MediaBrowser.Api.Playback.MediaInfoService: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 192000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "mp3,aac,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a,m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma,webm", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "mp3,aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "2", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "mp3,aac,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
```

**Comment by DirtyRacer1337** [comment]
Same as #36

**Comment by zkvvoob** [comment]
Thanks for replying so quickly! Do I wait for a formal release or is there another way to get the changes in my plugin instance?

**Comment by DirtyRacer1337** [comment]
@zkvvoob I finally find time for that. You can use [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)
