### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by josst10** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#38]
I am working on an Unraid server with Jellyfin in a Docker container.  I have uninstalled and re-installed the 2.4.2.42 multiple times and I still cannot get things to match any longer. It literally went from matching everything in my collection on Friday afternoon to the next minute, nothing! I thought maybe my IP was temporarily banned so gave it the weekend to settle down and I still cannot match anything. My logs should pretty much tell the story. 

Thanks for all the hard work!
```
[2021-02-22 12:33:46.679 -08:00] [INF] [17] PhoenixAdult.Provider: searchInfo.Name: Babes - 2015-10-29 - 3095421
[2021-02-22 12:33:46.684 -08:00] [INF] [17] PhoenixAdult.Provider: site: 6:0 (Babes)
[2021-02-22 12:33:46.684 -08:00] [INF] [17] PhoenixAdult.Provider: searchTitle: 3095421
[2021-02-22 12:33:46.684 -08:00] [INF] [17] PhoenixAdult.Provider: searchDate: 2015-10-29
[2021-02-22 12:33:46.685 -08:00] [INF] [17] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-22 12:33:48.035 -08:00] [ERR] [15] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
[2021-02-22 12:33:48.053 -08:00] [WRN] [15] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.50.39". Time (slow): 0:00:01.4025835. "http://192.168.50.7:8096/Items/RemoteSearch/Movie"
[2021-02-22 12:33:59.198 -08:00] [INF] [16] PhoenixAdult.Provider: searchInfo.Name: Big Naturals - 2015-10-14 - 8838
[2021-02-22 12:33:59.203 -08:00] [INF] [16] PhoenixAdult.Provider: site: 3:4 (BigNaturals)
[2021-02-22 12:33:59.203 -08:00] [INF] [16] PhoenixAdult.Provider: searchTitle: 8838
[2021-02-22 12:33:59.203 -08:00] [INF] [16] PhoenixAdult.Provider: searchDate: 2015-10-14
[2021-02-22 12:33:59.203 -08:00] [INF] [16] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-22 12:33:59.335 -08:00] [ERR] [15] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
[2021-02-22 12:34:42.904 -08:00] [INF] [5] PhoenixAdult.Provider: searchInfo.Name: BigNaturals - 8838
[2021-02-22 12:34:42.910 -08:00] [INF] [5] PhoenixAdult.Provider: site: 3:4 (BigNaturals)
[2021-02-22 12:34:42.910 -08:00] [INF] [5] PhoenixAdult.Provider: searchTitle: 8838
[2021-02-22 12:34:42.910 -08:00] [INF] [5] PhoenixAdult.Provider: searchDate: 
[2021-02-22 12:34:42.910 -08:00] [INF] [5] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-22 12:34:43.270 -08:00] [ERR] [26] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
[2021-02-22 12:34:57.188 -08:00] [INF] [29] PhoenixAdult.Provider: searchInfo.Name: Big Naturals - 2015-10-14 - fun in the sun
[2021-02-22 12:34:57.190 -08:00] [INF] [29] PhoenixAdult.Provider: site: 3:4 (BigNaturals)
[2021-02-22 12:34:57.190 -08:00] [INF] [29] PhoenixAdult.Provider: searchTitle: Fun In The Sun
[2021-02-22 12:34:57.190 -08:00] [INF] [29] PhoenixAdult.Provider: searchDate: 2015-10-14
[2021-02-22 12:34:57.190 -08:00] [INF] [29] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-22 12:34:57.862 -08:00] [ERR] [26] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
[2021-02-22 12:34:57.864 -08:00] [WRN] [26] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to "192.168.50.39". Time (slow): 0:00:00.6837787. "http://192.168.50.7:8096/Items/RemoteSearch/Movie"
[2021-02-22 12:40:09.137 -08:00] [INF] [32] PhoenixAdult.Provider: searchInfo.Name: Babes - 3076061
[2021-02-22 12:40:09.139 -08:00] [INF] [32] PhoenixAdult.Provider: site: 6:0 (Babes)
[2021-02-22 12:40:09.139 -08:00] [INF] [32] PhoenixAdult.Provider: searchTitle: 3076061
[2021-02-22 12:40:09.139 -08:00] [INF] [32] PhoenixAdult.Provider: searchDate: 
[2021-02-22 12:40:09.140 -08:00] [INF] [32] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.Network1service
[2021-02-22 12:40:09.531 -08:00] [ERR] [63] PhoenixAdult.Provider: Search error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JProperty.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.Network1service.Search(Int32[] siteNum, String searchTitle, Nullable`1 searchDate, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)"
```

**Comment by DirtyRacer1337** [comment]
Same as #37
