### ISSUE TITLE
Does Identify Work?

### ISSUE THREAD

**Issue by grravity** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#44]
Does the fields for Phoenix work, when using identify to manually identify unrecognized metadata in Jellyfin work?
I can't get anything besides blank results, I'm wondering if it's my search syntax?

**Comment by DirtyRacer1337** [comment]
Logs, examples?

**Comment by grravity** [comment]
[2021-03-22 15:53:22.872 -04:00] [ERR] Provider "PhoenixAdult" failed to retrieve search results
        System.NullReferenceException: Object reference not set to an instance of an object.
           at PhoenixAdult.Helpers.Helper.GetSiteNameFromTitle(String searchTitle)
           at PhoenixAdult.Provider.GetSearchResults(MovieInfo searchInfo, CancellationToken cancellationToken)
           at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
           at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

**Comment by grravity** [comment]
The ID I was trying was 
```
DOKS-506
```

I tried in both the Phoenix Movie ID and Phoenix ID Movie ID fields, same error

**Comment by grravity** [comment]
I just tried feeding a Pornhub URL to a video as well, no results, same logs.
According to your sites docs this seems like it should be supported?

It's not clear which of the PhoenixAdult fields to use to query, as they're two like I mentioned above. But either way that's not the issue seeing I tried both.

Jellyfin Win10 v10.7.0, Plugin v2.5.1.43,

**Comment by DirtyRacer1337** [comment]
You should use search fields, not technical.

**Comment by grravity** [comment]
There are two search fields, as I said one says
Phoenix Movie ID
the other says
Phoenix ID Movie ID

Either way, as I've stated neither provide results.

**Comment by DirtyRacer1337** [comment]
It's technical field, you should use name

**Comment by grravity** [comment]
Are you saying I have to specify the site name then the ID?
Like `JAVLibrary - DOKS-506`? 
Sorry I'm a bit confused.

**Comment by DirtyRacer1337** [comment]
For JAV it's not important science #25 and better use `JAV` it gives results from `R18` too.
`DOKS-506` works for me
```
[03:20:36.109] [INF] [  9] PhoenixAdult.Provider: searchInfo.Name: DOKS-506
[03:20:36.111] [INF] [  9] PhoenixAdult.Provider: newTitle: JAV DOKS-506
[03:20:36.115] [INF] [  9] PhoenixAdult.Provider: site: 42:0 (JAV)
[03:20:36.116] [INF] [  9] PhoenixAdult.Provider: searchTitle: DOKS 506
[03:20:36.116] [INF] [  9] PhoenixAdult.Provider: searchDate: 
[03:20:36.129] [INF] [  9] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkJAV
[03:20:36.149] [INF] [  9] PhoenixAdult.Provider: searchInfo.Name: JAVLibrary DOKS 506
[03:20:36.151] [INF] [  9] PhoenixAdult.Provider: site: 38:0 (JAVLibrary)
[03:20:36.152] [INF] [  9] PhoenixAdult.Provider: searchTitle: DOKS 506
[03:20:36.152] [INF] [  9] PhoenixAdult.Provider: searchDate: 
[03:20:36.153] [INF] [  9] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkJAVLibrary
[03:20:36.155] [DBG] [  9] PhoenixAdult.Provider: Requesting GET "http://www.javlibrary.com/en/vl_searchbyid.php?keyword=DOKS-506"
[03:20:36.714] [DBG] [ 27] PhoenixAdult.Provider: Requesting GET "http://www.javlibrary.com/en/?v=javli6qp6e"
[03:20:36.891] [DBG] [ 27] PhoenixAdult.Provider: Requesting GET "http://www.javlibrary.com/en/?v=javli6qp6e"
[03:20:58.688] [INF] [ 78] PhoenixAdult.Provider: PhoenixAdult ID: 42#0#38#0#SqHgsY9Laz3LDR5Gn6ymAXN
[03:20:58.692] [INF] [ 78] PhoenixAdult.Provider: PhoenixAdult ID: 38#0#SqHgsY9Laz3LDR5Gn6ymAXN
[03:20:58.693] [DBG] [ 78] PhoenixAdult.Provider: Requesting GET "http://www.javlibrary.com/en/?v=javli6qp6e"
[03:20:58.901] [DBG] [ 75] PhoenixAdult.Provider: Requesting GET "http://www.javlibrary.com/en/?v=javli6qp6e"
[03:20:59.105] [DBG] [ 75] PhoenixAdult.Provider: Requesting HEAD "http://pics.dmm.co.jp/mono/movie/adult/h_139doks506/h_139doks506pl.jpg"
[03:21:13.288] [DBG] [ 75] PhoenixAdult.Provider: Requesting GET "http://pics.dmm.co.jp/mono/movie/adult/h_139doks506/h_139doks506pl.jpg"
[03:21:13.755] [DBG] [ 77] PhoenixAdult.Provider: Requesting HEAD "http://pics.dmm.co.jp/mono/movie/adult/h_139doks506/h_139doks506pl.jpg"
[03:21:13.842] [DBG] [ 77] PhoenixAdult.Provider: Requesting GET "http://pics.dmm.co.jp/mono/movie/adult/h_139doks506/h_139doks506pl.jpg"
```

**Comment by grravity** [comment]
I uninstalled the plugin, then reinstalled and it seems to be working now. It might've been an issue when upgrading Jellyfin to 10.7.0, not sure. Sorry for the bother, thank you kindly.
