### ISSUE TITLE
TittyAttack not working?

### ISSUE THREAD

**Issue by PAHelper2** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#64]
Won't match: titty attack - 2021-04-10 - Nala Brooks 

**Include**
1. Jellyfin
2. Latest dev version you gave me
3. I can't get to the scene on the website
4. TittyAttack.21.04.10.Nala.Brooks.Let.Em.Bounce.XXX.XviD-iPT.Team.mp4
5. Log File below:
```
[2021-04-29 16:28:59.107 +00:00] [INF] [43] PhoenixAdult.Provider: searchInfo.Name: titty attack - 2021-04-10 - Nala Brooks 
[2021-04-29 16:28:59.115 +00:00] [INF] [43] PhoenixAdult.Provider: site: 24:15 (TittyAttack)
[2021-04-29 16:28:59.115 +00:00] [INF] [43] PhoenixAdult.Provider: searchTitle: Nala Brooks
[2021-04-29 16:28:59.116 +00:00] [INF] [43] PhoenixAdult.Provider: searchDate: 2021-04-10
[2021-04-29 16:28:59.117 +00:00] [INF] [43] PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMylf
[2021-04-29 16:29:08.248 +00:00] [ERR] [61] PhoenixAdult.Provider: Request error: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8191)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
[2021-04-29 16:29:12.383 +00:00] [ERR] [51] PhoenixAdult.Provider: Request error: Error connecting to FlareSolverr server: System.Net.Http.HttpRequestException: Cannot assign requested address (localhost:8191)
 ---> System.Net.Sockets.SocketException (99): Cannot assign requested address
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at FlareSolverrSharp.Solvers.FlareSolverr.<>c__DisplayClass5_0.<<Solve>b__0>d.MoveNext()
[2021-04-29 16:29:12.386 +00:00] [WRN] [51] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://jellyfin.XXX.com:443/Items/RemoteSearch/Movie" to "172.18.0.1" in 0:00:17.8129796 with Status Code 200
```

**Comment by PAHelper2** [comment]
I installed flaresolverr and got farther.  I see that other TittyAttack scenes work.  This problem appears to be specific to this one scene, which I guess is not present on the site.
