### ISSUE TITLE
CleanupGenres Scheduled Task Failed

### ISSUE THREAD

**Issue by xjasonlyu** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#70]
**Describe the bug**

```
Method not found: 'System.Collections.Generic.Dictionary`2<system.string,system.string> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
at PhoenixAdult.ScheduledTasks.CleanupGenres.&lt;&gt;c.<execute>b__10_0(BaseItem o)
at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
at PhoenixAdult.ScheduledTasks.CleanupGenres.Execute(CancellationToken cancellationToken, IProgress`1 progress)
at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)</execute></system.string,system.string>
```

**Include**

1. on Emby (4.6.0)
2. Latest Stable Version

**Solution**

https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/blob/d04163509038a11990299f2f2d7995f89628cb79/Jellyfin.Plugin.PhoenixAdult/ScheduledTasks/CleanupGenres.cs#L35

=>

```cs
var items = _libraryManager.GetItemList(new InternalItemsQuery
            {
                MediaTypes = new[] {MediaType.Video},
                IncludeItemTypes = new[] {nameof(Movie)},
                HasAnyProviderId = new[] {Plugin.Instance.Name}
            }).ToList();
```

**Comment by DirtyRacer1337** [comment]
Try on [Nightly Build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)

**Comment by xjasonlyu** [comment]
Not working

**Comment by DirtyRacer1337** [comment]
Make sure you using nightly build plugin, I just tested it and that's helps

**Comment by MRobi1** [comment]
Seeing the same errors. On the latest nightly, using Emby 4.6.1

`2021-05-26 11:56:09.649 Error TaskManager: Error
	*** Error Report ***
	Version: 4.6.1.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.78-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.78-1 (Mon, 30 Nov 2020 10:57:47 +0100)
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 16
	Data path: /config
	Application path: /app/emby
	System.MissingMethodException: System.MissingMethodException: Method not found: 'Void MediaBrowser.Controller.Library.ILibraryManager.UpdatePeople(MediaBrowser.Controller.Entities.BaseItem, System.Collections.Generic.List`1<MediaBrowser.Controller.Entities.PersonInfo>)'.
	   at PhoenixAdult.ScheduledTasks.CleanupActors.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at PhoenixAdult.ScheduledTasks.CleanupActors.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
	Source: PhoenixAdult
	TargetSite: Void MoveNext()`

`2021-05-26 12:06:44.553 Error TaskManager: Error
	*** Error Report ***
	Version: 4.6.1.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.78-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.78-1 (Mon, 30 Nov 2020 10:57:47 +0100)
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 16
	Data path: /config
	Application path: /app/emby
	System.TypeLoadException: System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Entities.Movies.BoxSet' from assembly 'MediaBrowser.Controller, Version=4.6.1.0, Culture=neutral, PublicKeyToken=null'.
	   at PhoenixAdult.ScheduledTasks.AddCollection.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at PhoenixAdult.ScheduledTasks.AddCollection.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
	Source: PhoenixAdult
	TargetSite: Void MoveNext()`
`2021-05-26 12:07:04.445 Error TaskManager: Error
	*** Error Report ***
	Version: 4.6.1.0
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
	Operating system: Linux version 5.4.78-1-pve (build@pve) (gcc version 8.3.0 (Debian 8.3.0-6)) #1 SMP PVE 5.4.78-1 (Mon, 30 Nov 2020 10:57:47 +0100)
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: app/emby/System.Private.CoreLib.dll
	Processor count: 16
	Data path: /config
	Application path: /app/emby
	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> MediaBrowser.Controller.Entities.BaseItem.get_ProviderIds()'.
	   at PhoenixAdult.ScheduledTasks.CleanupGenres.<>c.<Execute>b__10_0(BaseItem o)
	   at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
	   at PhoenixAdult.ScheduledTasks.CleanupGenres.Execute(CancellationToken cancellationToken, IProgress`1 progress)
	   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
	Source: PhoenixAdult
	TargetSite: Boolean <Execute>b__10_0(MediaBrowser.Controller.Entities.BaseItem)`

**Comment by DirtyRacer1337** [comment]
I found problem, emby nighty build zip doesn't get updates since 36cef7b2435c90e3a46be2b5638cc119b458fd96
Should work now

**Comment by MRobi1** [comment]
> I found problem, emby nighty build zip doesn't get updates since [36cef7b](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/commit/36cef7b2435c90e3a46be2b5638cc119b458fd96)
> Should work now

That fixed it! Thanks
