### ISSUE TITLE
The White Boxxx not working.

### ISSUE THREAD

**Issue by anon-127** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#71]
Filename: TheWhiteBoxxx - More than friends.mp4

It doesn't scrape metadata. I tried porndoe title too but it didn't work

Manually found url:

- https://porndoe.com/video/613686/european-heidi-romanova-and-lorena-garcia-in-passionate-lesbian-fuck
- https://letsdoeit.com/watch/5333/more-than-friends.en.html

**Comment by DirtyRacer1337** [comment]
`TheWhiteBoxxx - More than friends`, works for me can you send logs?

**Comment by anon-127** [comment]
How to get logs? OS: linux

**Comment by DirtyRacer1337** [comment]
data directory/log

https://jellyfin.org/docs/general/administration/configuration.html#data-directory
https://jellyfin.org/docs/general/administration/configuration.html#log-directory

**Comment by anon-127** [comment]
```
Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "PhoenixAdult, Version=2.5.2.44, Culture=neutral, PublicKeyToken=null" from "/var/lib/jellyfin/plugins/PhoenixAdult_2.5.2.44/Jellyfin.Plugin.PhoenixAdult.dll"
Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "PhoenixAdult" "2.5.2.44"
PhoenixAdult.Provider: searchInfo.Name: wowg.18.02.15.nancy.a.and.sybil.girlfriends.forever
PhoenixAdult.Provider: newTitle: MetadataAPI Wowg 18 02 15 Nancy A And Sybil Girlfriends Forever
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Wowg Nancy A And Sybil Girlfriends Forever
PhoenixAdult.Provider: searchDate: 2018-02-15
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: HayliSanders_NancyA_CaressMeHot
PhoenixAdult.Provider: newTitle: MetadataAPI Haylisanders Nancya Caressmehot
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Haylisanders Nancya Caressmehot
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: Sybil A, Hayli Sanders - Obsessed With Amazing Pussy Smell
PhoenixAdult.Provider: newTitle: MetadataAPI Sybil A Hayli Sanders Obsessed With Amazing Pussy Smell
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Sybil A Hayli Sanders Obsessed With Amazing Pussy Smell
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#7R9ijCRWAQHGTRtWX22cFY1QoeGJUGYd5Jv2G
PhoenixAdult.Provider: searchInfo.Name: HQporner - Aislin, Hayli And Nancy
PhoenixAdult.Provider: newTitle: MetadataAPI Hqporner Aislin Hayli And Nancy
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Hqporner Aislin Hayli And Nancy
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: TheWhiteBoxxx - More than friends
PhoenixAdult.Provider: site: 29:1 (TheWhiteBoxxx)
PhoenixAdult.Provider: searchTitle: More Than Friends
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkPorndoe
PhoenixAdult.Provider: searchInfo.Name: Silvie Luca and Silvie Girl Sex Lesson
PhoenixAdult.Provider: newTitle: MetadataAPI Silvie Luca And Silvie Girl Sex Lesson
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Silvie Luca And Silvie Girl Sex Lesson
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: Nancy A & Sabrisse - Passionate Lesbians Munching Pussy
PhoenixAdult.Provider: newTitle: MetadataAPI Nancy A Sabrisse Passionate Lesbians Munching Pussy
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Nancy A Sabrisse Passionate Lesbians Munching Pussy
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: Sybil A Baby Nicols  An Indecent Story
PhoenixAdult.Provider: newTitle: MetadataAPI Sybil A Baby Nicols An Indecent Story
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Sybil A Baby Nicols An Indecent Story
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: Little Caprice - Fuck The Stress Away (14.11
PhoenixAdult.Provider: newTitle: MetadataAPI Little Caprice Fuck The Stress Away 14 11
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Little Caprice Fuck The Stress Away 14 11
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: searchInfo.Name: WowGirls.SlySeductress
PhoenixAdult.Provider: newTitle: MetadataAPI Wowgirls Slyseductress
PhoenixAdult.Provider: site: 48:0 (MetadataAPI)
PhoenixAdult.Provider: searchTitle: Wowgirls Slyseductress
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkMetadataAPI
PhoenixAdult.Provider: PhoenixAdult ID: 44#3#2Kxc4BA8m1DKH4XhihLks
PhoenixAdult.Provider: PhoenixAdult ID: 44#3#9gbM1UrcLSiECcLNWmS6YUW5jE
PhoenixAdult.Provider: PhoenixAdult ID: 44#2#3fa4VrFAzoLktL
PhoenixAdult.Provider: PhoenixAdult ID: 44#2#4xFZ667ckeA4DAC1nr
PhoenixAdult.Provider: PhoenixAdult ID: 44#2#2T9dw1k6xDXuUZd6DvKAN9JqrkwBkyGr3xsi
PhoenixAdult.Provider: searchInfo.Name: TheWhiteBoxxx - sensual-lesbian-loving-with-stunning-czech-caprice-and-tracy-loves-1
PhoenixAdult.Provider: site: 29:1 (TheWhiteBoxxx)
PhoenixAdult.Provider: searchTitle: Sensual Lesbian Loving With Stunning Czech Caprice And Tracy Loves 1
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkPorndoe
PhoenixAdult.Provider: PhoenixAdult ID: 44#2#yoAVB2ToCiUQQG5NLFie1gvPUs7LUQS
PhoenixAdult.Provider: searchInfo.Name: TheWhiteBoxxx - Sabrisse, Nancy A (Eurpean Lesbians Make Sweet, Sweet Love)
PhoenixAdult.Provider: site: 29:1 (TheWhiteBoxxx)
PhoenixAdult.Provider: searchTitle: Sabrisse Nancy A Eurpean Lesbians Make Sweet Sweet Love
PhoenixAdult.Provider: searchDate: 
PhoenixAdult.Provider: provider: PhoenixAdult.Sites.NetworkPorndoe
PhoenixAdult.Provider: PhoenixAdult ID: 44#2#JRnTFY4AE6CqPoBmusH
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#XzqVhoX7M6PEfcUYGF2SoJtxGBGH5KtC3g8e5fxUYp3iujzvi9ci3
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#2L1Aj9vJApNYn4R14j9A3
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#3v8ueyQyPvxuJdUQjme6d5giNetfo
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#8gbcPKg3Ry8j7rGxjo6UJbryd8xWfafSy2BNx8ku4C9ecQxmYN3ggiY9CPC5Dv3jKvM
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#QdpokF5a
PhoenixAdult.Provider: Update error: "Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at PhoenixAdult.Sites.NetworkStrike3.GetDataFromAPI(String url, CancellationToken cancellationToken)
   at PhoenixAdult.Sites.NetworkStrike3.Update(Int32[] siteNum, String[] sceneID, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)"
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#JRN9TYWcjNBTRk3FPKH
PhoenixAdult.Provider: PhoenixAdult ID: 44#1#7QfMNh4hm2BrHJ75kWBihXXR72fQjGj5e5E5z

```

**Comment by DirtyRacer1337** [comment]
try on [nighty build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)

**Comment by anon-127** [comment]
Nightly works thanks for the assitance

**Comment by anon-127** [comment]
stopped working again on nightly.

**Comment by DirtyRacer1337** [comment]
Fixed in 8c7226f04e57a102d4b23c93a51e73f45d1ae3ee

**Comment by anon-127** [comment]
Is there a way to auto update nightly in jellyfin?

**Comment by DirtyRacer1337** [comment]
nope
