### ISSUE TITLE
Plugin throws error in latest Emby server

### ISSUE THREAD

**Issue by radu-solomon-sw** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#73]
**Describe the bug**
Emby 4.7 plugin is throwing and error and not returning any results. Same search in jellyfin works

1. Emby 4.7
2. Plugin Version: 2.6.1.45
3. Any scene
4. Any file name
5. Error from the log

2021-05-30 12:02:52.508 Error App: Error in PhoenixAdult
	*** Error Report ***
	Version: 4.7.0.1
	Command line: C:\Users\radus\AppData\Roaming\Emby-Server\system\EmbyServer.dll -noautorunwebapp
	Operating system: Microsoft Windows 10.0.19043
	Framework: .NET Core 3.1.13
	OS/Process: x64/x64
	Runtime: C:/Users/radus/AppData/Roaming/Emby-Server/system/System.Private.CoreLib.dll
	Processor count: 12
	Data path: C:\Users\radus\AppData\Roaming\Emby-Server\programdata
	Application path: C:\Users\radus\AppData\Roaming\Emby-Server\system
	System.MissingMethodException: System.MissingMethodException: Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> MediaBrowser.Controller.Providers.ItemLookupInfo.get_ProviderIds()'.
	   at PhoenixAdult.Provider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
	   at PhoenixAdult.Provider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)
	   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(BaseItem originalItem, MetadataResult`1 temp, LibraryOptions libraryOptions, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
	Source: PhoenixAdult
	TargetSite: Void MoveNext()

**Comment by DirtyRacer1337** [comment]
Latest emby (4.6) supported on [nightly build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly)

**Comment by radu-solomon** [comment]
Thank you. That works.
