### ISSUE TITLE
Manyvids does not return any results

### ISSUE THREAD

**Issue by barobab** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#83]
I hope i am just doing something wrong, but i can't get identifying manyvids videos to work.
For my tests, i have just picked a random video id like `1995625`, and tried to identify a video as `Manyvids - 1995625`.
I set the logs to debug and this is what happens when trying to identify a manyvids video:

logs for `Manyvids - 1995625`
```
[2021-07-20 22:35:25.211 +00:00] [INF] [30] PhoenixAdult.Plugin: searchInfo.Name: manyvids - 1995625
[2021-07-20 22:35:25.213 +00:00] [INF] [30] PhoenixAdult.Plugin: site: 50:0 (Manyvids)
[2021-07-20 22:35:25.213 +00:00] [INF] [30] PhoenixAdult.Plugin: searchTitle: 1995625
[2021-07-20 22:35:25.213 +00:00] [INF] [30] PhoenixAdult.Plugin: searchDate: 
[2021-07-20 22:35:25.213 +00:00] [DBG] [30] Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: List of registered output formatters, in the following order: ["Jellyfin.Server.Formatters.PascalCaseJsonProfileFormatter", "Jellyfin.Server.Formatters.CamelCaseJsonProfileFormatter", "Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter", "Jellyfin.Server.Formatters.CssOutputFormatter", "Jellyfin.Server.Formatters.XmlOutputFormatter"]
[2021-07-20 22:35:25.213 +00:00] [DBG] [30] Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Attempting to select an output formatter based on Accept header '["application/json"]' and explicitly specified content types '["application/json", "application/json; profile=\"CamelCase\"", "application/json; profile=\"PascalCase\""]'. The content types in the accept header must be a subset of the explicitly set content types.
[2021-07-20 22:35:25.213 +00:00] [DBG] [30] Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: Selected output formatter '"Jellyfin.Server.Formatters.PascalCaseJsonProfileFormatter"' and content type '"application/json"' to write the response.
[2021-07-20 22:35:25.213 +00:00] [INF] [30] Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor: Executing "OkObjectResult", writing value of type '"System.Collections.Generic.List`1[[MediaBrowser.Model.Providers.RemoteSearchResult, MediaBrowser.Model, Version=10.7.6.0, Culture=neutral, PublicKeyToken=null]]"'.
[2021-07-20 22:35:25.213 +00:00] [DBG] [30] Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
[2021-07-20 22:35:25.213 +00:00] [INF] [30] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action "Jellyfin.Api.Controllers.ItemLookupController.GetMovieRemoteSearchResults (Jellyfin.Api)" in 2.9659ms
[2021-07-20 22:35:25.213 +00:00] [INF] [30] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '"Jellyfin.Api.Controllers.ItemLookupController.GetMovieRemoteSearchResults (Jellyfin.Api)"'
[2021-07-20 22:35:25.213 +00:00] [DBG] [30] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMABPPT7DOK2"" completed keep alive response.
[2021-07-20 22:35:25.213 +00:00] [INF] [30] Microsoft.AspNetCore.Hosting.Diagnostics: Request finished HTTP/1.1 POST http://localhost/jellyfin/Items/RemoteSearch/Movie application/json 183 - 200 - application/json;+charset=utf-8 13.9435ms
[2021-07-20 22:35:27.982 +00:00] [INF] [34] Microsoft.AspNetCore.Hosting.Diagnostics: Request starting HTTP/1.1 GET http://localhost/jellyfin/System/Logs/Log?name=log_20210720.log&api_key=*** - -
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "/System/Logs/Log" does not match a supported file type
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware: The request path "" does not match the path filter
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: 1 candidate(s) found for the request path '"/System/Logs/Log"'
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.Routing.Matching.DfaMatcher: Endpoint '"Jellyfin.Api.Controllers.SystemController.GetLogFile (Jellyfin.Api)"' with route pattern '"System/Logs/Log"' is valid for the request path '"/System/Logs/Log"'
[2021-07-20 22:35:27.982 +00:00] [DBG] [34] Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware: Request matched endpoint '"Jellyfin.Api.Controllers.SystemController.GetLogFile (Jellyfin.Api)"'
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: "CustomAuthentication" was successfully authenticated.
[2021-07-20 22:35:27.983 +00:00] [INF] [34] Microsoft.AspNetCore.Authorization.DefaultAuthorizationService: Authorization was successful.
[2021-07-20 22:35:27.983 +00:00] [INF] [34] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executing endpoint '"Jellyfin.Api.Controllers.SystemController.GetLogFile (Jellyfin.Api)"'
[2021-07-20 22:35:27.983 +00:00] [INF] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Route matched with "{action = \"GetLogFile\", controller = \"System\"}". Executing controller action with signature "Microsoft.AspNetCore.Mvc.ActionResult GetLogFile(System.String)" on controller "Jellyfin.Api.Controllers.SystemController" ("Jellyfin.Api").
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Execution plan of "authorization" filters (in the following order): ["None"]
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Execution plan of "resource" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter"]
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Execution plan of "exception" filters (in the following order): ["None"]
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter", "Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)", "Microsoft.AspNetCore.Mvc.ProducesAttribute (Order: 0)"]
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executing controller factory for controller "Jellyfin.Api.Controllers.SystemController" ("Jellyfin.Api")
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed controller factory for controller "Jellyfin.Api.Controllers.SystemController" ("Jellyfin.Api")
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Attempting to bind parameter '"name"' of type '"System.String"' ...
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder: Attempting to bind parameter '"name"' of type '"System.String"' using the name '"name"' in request data ...
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinder: Done attempting to bind parameter '"name"' of type '"System.String"'.
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Done attempting to bind parameter '"name"' of type '"System.String"'.
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Attempting to validate the bound parameter '"name"' of type '"System.String"' ...
[2021-07-20 22:35:27.983 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder: Done attempting to validate the bound parameter '"name"' of type '"System.String"'.
[2021-07-20 22:35:27.984 +00:00] [INF] [34] Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor: Executing "FileStreamResult", sending file with download name '""' ...
[2021-07-20 22:35:27.984 +00:00] [DBG] [34] Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor: The file result has not been enabled for processing range requests. To enable it, set the property 'EnableRangeProcessing' on the result to 'true'.
[2021-07-20 22:35:27.984 +00:00] [DBG] [32] Microsoft.AspNetCore.ResponseCompression.ResponseCompressionProvider: No response compression available for HTTPS requests. See ResponseCompressionOptions.EnableForHttps.
[2021-07-20 22:35:27.990 +00:00] [INF] [27] Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Executed action "Jellyfin.Api.Controllers.SystemController.GetLogFile (Jellyfin.Api)" in 7.0463ms
[2021-07-20 22:35:27.990 +00:00] [INF] [27] Microsoft.AspNetCore.Routing.EndpointMiddleware: Executed endpoint '"Jellyfin.Api.Controllers.SystemController.GetLogFile (Jellyfin.Api)"'
[2021-07-20 22:35:27.991 +00:00] [WRN] [27] Jellyfin.Server.Middleware.ExceptionMiddleware: The response has already started, the exception middleware will not be executed.
[2021-07-20 22:35:27.991 +00:00] [ERR] [27] Microsoft.AspNetCore.Server.Kestrel: Connection id ""0HMABPPT7DOK2"", Request id ""0HMABPPT7DOK2:00000012"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Response Content-Length mismatch: too many bytes written (1937896 of 1937242).
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ThrowTooManyBytesWritten(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.VerifyAndUpdateWrite(Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.WritePipeAsync(ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionBody.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Http.StreamCopyOperationInternal.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileResultExecutorBase.WriteFileAsync(HttpContext context, Stream fileStream, RangeItemHeaderValue range, Int64 rangeLength)
   at Microsoft.AspNetCore.Mvc.Infrastructure.FileStreamResultExecutor.ExecuteAsync(ActionContext context, FileStreamResult result)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.BaseUrlRedirectionMiddleware.Invoke(HttpContext httpContext, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

It looks like it's just not actually sending a request to get information. In contrast to that, here are the logs for a random pornhub video:

logs for `pornhub - ph6053d4f5eab2d`:
```log
[2021-07-20 22:45:31.674 +00:00] [INF] [134] PhoenixAdult.Plugin: searchInfo.Name: pornhub - ph6053d4f5eab2d
[2021-07-20 22:45:31.675 +00:00] [INF] [134] PhoenixAdult.Plugin: site: 27:0 (Pornhub)
[2021-07-20 22:45:31.675 +00:00] [INF] [134] PhoenixAdult.Plugin: searchTitle: Ph6053d4f5eab2d
[2021-07-20 22:45:31.675 +00:00] [INF] [134] PhoenixAdult.Plugin: searchDate: 
[2021-07-20 22:45:31.675 +00:00] [INF] [134] PhoenixAdult.Plugin: provider: PhoenixAdult.Sites.SitePornhub
[2021-07-20 22:45:31.703 +00:00] [DBG] [134] PhoenixAdult.Plugin: Requesting GET "https://www.pornhub.com/view_video.php?viewkey=Ph6053d4f5eab2d"
[2021-07-20 22:45:33.162 +00:00] [DBG] [135] PhoenixAdult.Plugin: Requesting GET "https://www.pornhub.com/view_video.php?viewkey=Ph6053d4f5eab2d"
[2021-07-20 22:45:33.354 +00:00] [DBG] [135] Microsoft.AspNetCore.Mvc.Infrastructure.DefaultOutputFormatterSelector: List of registered output formatters, in the following order: ["Jellyfin.Server.Formatters.PascalCaseJsonProfileFormatter", "Jellyfin.Server.Formatters.CamelCaseJsonProfileFormatter", "Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StringOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.StreamOutputFormatter", "Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter", "Jellyfin.Server.Formatters.CssOutputFormatter", "Jellyfin.Server.Formatters.XmlOutputFormatter"]
```

And this one does seem to send a proper request (and returns proper results).

I am on the latest version (`2.6.2.46`) btw.

**Comment by DirtyRacer1337** [comment]
ManyVids only available for [nightly build](https://github.com/DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult/releases/tag/nightly) for now
