### ISSUE TITLE
NetworkStrike3 doesn’t work properly

### ISSUE THREAD

**Issue by gythialy** [DirtyRacer1337/Jellyfin.Plugin.PhoenixAdult#85]
**Describe the bug**

It can download the cover images, but you cannot update the other information, such as actor information

**Include**
1. Jellyfin or Emby
Emby 4.6.4.0
2. Plugin Version
 PhoenixAdult 10.7.0.0
3. Scene URL
https://www.vixen.com/videos/a-club-vxn-vacation-3
4. File Name
Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4
5. Log File
```
2021-07-26 14:04:14.332 Info PhoenixAdult: searchInfo.Name: Vixen-21.07.23-A Club VXN Vacation 3
2021-07-26 14:04:14.334 Info PhoenixAdult: site: 44:2 (Vixen)
2021-07-26 14:04:14.334 Info PhoenixAdult: searchTitle: A Club VXN Vacation 3
2021-07-26 14:04:14.334 Info PhoenixAdult: searchDate: 2021-07-23
2021-07-26 14:04:14.335 Info PhoenixAdult: provider: PhoenixAdult.Sites.NetworkStrike3
2021-07-26 14:04:14.335 Debug PhoenixAdult: Requesting GET "http://www.vixen.com/graphql?query=%7BsearchVideos(input:%7Bquery:%22A%20Club%20VXN%20Vacation%203%22,site:VIXEN,first:10%7D)%7Bedges%7Bnode%7BvideoId,title,releaseDate,slug,images%7Blisting%7Bsrc%7D%7D%7D%7D%7D%7D"
2021-07-26 14:04:27.301 Info App: Setting provider id's to item 9919-Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]: {"PhoenixAdult":"44#2#6yas1uL5Rx1sk7P5ADpexvxwKRzdg"}
2021-07-26 14:04:27.307 Debug SqliteItemRepository: Public GetItemLinks
2021-07-26 14:04:27.310 Debug App: ApplySearchResult
2021-07-26 14:04:27.310 Debug App: Running FFProbeProvider for /vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4
2021-07-26 14:04:27.310 Info MediaProbeManager: ProcessRun 'ffprobe' Execute: /bin/ffprobe -i file:"/mnt/ooxx/vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4" -threads 0 -v info -print_format json -show_streams -show_chapters -show_format -show_data
2021-07-26 14:04:27.313 Debug MediaProbeManager: ProcessRun 'ffprobe' Started.
2021-07-26 14:04:27.390 Info MediaProbeManager: ProcessRun 'ffprobe' Process exited with code 0
2021-07-26 14:04:27.404 Debug App: Running Provider for /vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4
2021-07-26 14:04:27.404 Info PhoenixAdult: PhoenixAdult ID: 44#2#6yas1uL5Rx1sk7P5ADpexvxwKRzdg
2021-07-26 14:04:27.405 Debug PhoenixAdult: Requesting GET "http://www.vixen.com/graphql?query=%7BfindOneVideo(input:%7Bslug:%22a-club-vxn-vacation-3%22,site:VIXEN%7D)%7BvideoId,title,description,releaseDate,models%7Bname,slug,images%7Blisting%7Bhighdpi%7Bdouble%7D%7D%7D%7D,directors%7Bname%7D,categories%7Bname%7D,carousel%7Blisting%7Bhighdpi%7Btriple%7D%7D%7D%7D%7D"
2021-07-26 14:04:28.035 Error PhoenixAdult: Update error: "System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.
   at Newtonsoft.Json.Linq.JToken.get_Item(Object key)
   at PhoenixAdult.Sites.NetworkStrike3.Update(Int32[] siteNum, String[] sceneID, CancellationToken cancellationToken)
   at PhoenixAdult.Provider.GetMetadata(MovieInfo info, CancellationToken cancellationToken)"
2021-07-26 14:04:28.036 Debug App: Provider returned no metadata for /vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4
2021-07-26 14:04:28.036 Debug App: Running Movies for /vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4
2021-07-26 14:04:29.461 Debug PhoenixAdult: Requesting GET "http://www.vixen.com/graphql?query=%7BfindOneVideo(input:%7Bslug:%22a-club-vxn-vacation-3%22,site:VIXEN%7D)%7BvideoId,title,description,releaseDate,models%7Bname,slug,images%7Blisting%7Bhighdpi%7Bdouble%7D%7D%7D%7D,directors%7Bname%7D,categories%7Bname%7D,carousel%7Blisting%7Bhighdpi%7Btriple%7D%7D%7D%7D%7D"
2021-07-26 14:04:29.463 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic01_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.469 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic02_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.473 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic03_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.480 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic04_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.483 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic05_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.485 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic06_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.489 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic07_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.492 Debug PhoenixAdult: Requesting HEAD "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic08_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.683 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic08_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.685 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic07_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.687 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic02_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.696 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic04_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.700 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic05_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.720 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic06_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.720 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic01_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:29.725 Debug PhoenixAdult: Requesting GET "https://cdn.vixen.com/scene/TOURPHOTOTHUMB/102742/1626341667389/tn_pic03_880x495.jpg?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9jZG4udml4ZW4uY29tL3NjZW5lL1RPVVJQSE9UT1RIVU1CLzEwMjc0Mi8xNjI2MzQxNjY3Mzg5LyouanBnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjI3NzQwMzU3fSwiSXBBZGRyZXNzIjp7IkFXUzpTb3VyY2VJcCI6IjU4LjE1Mi44MS44Ni8zMiJ9fX1dfQ__&Key-Pair-Id=K18SM53O8A1CFO&Signature=ahwBffvet5Tt5s~gKE6O~d12w2FkTf175xFv6ewenvj5pLUIihoPFKvWDefHchlDa5LQhOqQFxHK2lJ9cwYJAK2BAu4ejnAoKev3q9R-6Otf7iifZmyhTGdkigsSZVpj4HkCo3JtkpVbJS1obr8mAY7s4QHZkov9yELBqYKOBkpjTMxbymqXo1lwTcy9CA-5kcPo1rFi31fKxqW35QQ~kd2kUduhSoMzntdd8OOZ8HckFXcLpVSfMqRt7X1AFbg3tbewKUZQK9hLr~Qn38yGTDeyCc0BDoNv9hopP3PkOSJ7JEIuo8z-8ju6C34~D9ev1lbySUJpglRZz9vD0JYIZg__"
2021-07-26 14:04:30.172 Debug App: Running MoviesImages for /vixen/Vixen.21.07.23.Lika.Star.And.Mary.Rock.XXX.1080p.MP4-NBQ[rarbg]/vixen.21.07.23.lika.star.and.mary.rock.mp4

```

**Comment by DirtyRacer1337** [comment]
Fixed in 9c6aca01846717d9feec4643b0f01044bbc72c19
